# Generated by Django 4.2.8 on 2024-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_testinglab_quantity_testinglab_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinglab',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='testinglab',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
