# Generated by Django 4.2.8 on 2024-03-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_testinglab_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbanks',
            old_name='bloodtype',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='bloodbanks',
            old_name='receiver_name',
            new_name='donor_name',
        ),
    ]
